FROM azul/zulu-openjdk-alpine:17.0.5-17.38.21-jre-headless-arm64 as build

MAINTAINER jzheng jiangzheng1023@foxmail.com

RUN mkdir /app

WORKDIR /app

ENV _JAVA_OPTIONS="-Xmx256m -Xms128m"
ENV SPRING_PROFILES_ACTIVE=dev,api-docs
ENV MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
ENV SPRING_DATASOURCE_URL="jdbc:mysql://mysql_default:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
ENV SPRING_LIQUIBASE_URL="jdbc:mysql://mysql_default:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
ENV JHIPSTER_SLEEP=30

ARG JAR_FILE="target/*.jar"

COPY ${JAR_FILE} /app/blog.jar

EXPOSE 8080

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar /app/blog.jar" ]
